spring.application.name=jwt


server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt
spring.datasource.username=postgres
spring.datasource.password=Ndt2501><

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.expired=300000
jwt.sercret-key=hunghx123456789hsduhufdhfudhufduhfuhduhfudhufhdu74853sdfgsdhbfhbdshbfhbdsdfsdsfsd35349653463645646